[package]
name = "cargo-extract"
version = "0.3.3"
edition = "2024"
description = "Cargo subcommand to extract information from Cargo.toml files"
repository = "https://github.com/LimeEng/cargo-extract/"
license = "MIT"
categories = [
    "command-line-utilities",
    "development-tools::build-utils",
    "development-tools::cargo-plugins",
]

exclude = [".github/**"]

[dependencies]
clap = "4"
toml = { version = "1", features = ["preserve_order"] }
unicode-width = "0.2"

[dev-dependencies]
criterion = "0.8"
indoc = "2"
tempfile = "3"

[[bench]]
name = "extract"
harness = false

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
map_unwrap_or = "allow"

[lints.rustdoc]
all = { level = "deny", priority = -1 }
